ARCH_X86_DIR := arch/x86

LINKAGE += \
	$(ARCH_X86_DIR)/multiboot.o \
	$(ARCH_X86_DIR)/vm.o \
	$(ARCH_X86_DIR)/pci.o \
	$(ARCH_X86_DIR)/vbe.o \
	$(ARCH_X86_DIR)/irq.o \
	$(ARCH_X86_DIR)/arch.o \
	$(ARCH_X86_DIR)/task.o \
	$(ARCH_X86_DIR)/timer.o \
	$(ARCH_X86_DIR)/spinlock.o \
	$(ARCH_X86_DIR)/interrupts.o \
	$(ARCH_X86_DIR)/framebuffer.o \
	$(ARCH_X86_DIR)/asm-interrupts.o

#	$(ARCH_X86_DIR)/multiboot.o \